spring.application.name=generador-plantillas

# Database Configuration
spring.datasource.url=${DATABASE_PUBLIC_URL:jdbc:postgresql://localhost:5432/DBPlantillas}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

# Configuracion de Rendimiento
spring.jpa.open-in-view=false


# Muestra todo el proceso de los filtros de seguridad y acceso denegado
logging.level.org.springframework.security=TRACE

# Muestra cómo se reciben las peticiones y a qué controladores se dirigen
logging.level.org.springframework.web=DEBUG

# Opcional: Muestra los valores de los parámetros en las consultas SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE